package core

enum class SolverState
{
    INPUT,
    PROBABILITY_DEFINE,
    PROBABILITY_MUTUAL,
    PVAR_DEFINE,
    PVAR_PARAMS,
    DRAW_DEFINE,
    CINT_DEFINE,
    OBJECT_DEFINE,
    OBJECT_SAMPLE,
    OBJECT_BOX,
    OBJECT_REGION,
    BAYESIAN_PARENTS,
    BAYESIAN_CHILDREN,
    SEQ_DEFINE,
    JVAR_DEFINE,
    JVAR_PARAMS,
    QUERY_PROBABILITY,
    QUERY_MUTUAL,
    QUERY_EXVAL
}
